replicas: 1

resources:
  requests:
    memory: "512M"
    cpu: 1

persistence:
  size: "40G"

rbac:
  create: true
  serviceAccountName: "opensearchassumedrole"
  automountServiceAccountToken: false

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "os-admin-credentials"
        key: "password"
