replicas: 1
resources:
  requests:
    memory: "2Gi"
    cpu: 1
persistence:
  size: "40G"
rbac:
  create: true
  serviceAccountName: "opensearchassumedrole"
  automountServiceAccountToken: false

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "SuperSecretR0d3nt"
